-- Seed gerado a partir do seu catálogo atual no GitHub (jogosInstantGaming)
-- Rode isso DEPOIS do schema.sql, no mesmo SQL Editor do Supabase.
-- Os preços vêm em branco (NULL) porque o site antigo não guardava preço --
-- você pode preencher depois direto na tabela (Table Editor) quando for editar cada jogo.

insert into games (name, slug, store, affiliate_url) values
  ('Nintendo eshop 50', 'nintendo-eshop-50', 'Instant Gaming', 'https://www.instant-gaming.com/en/13529-buy-nintendo-eshop-card-50-brl-r-50-card-switch-switch-2-game-nintendo-eshop-brazil//?igr=eupqs'),
  ('Nintendo eShop 100', 'nintendo-eshop-100', 'Instant Gaming', 'https://www.instant-gaming.com/en/13530-buy-nintendo-eshop-card-100-brl-r-100-card-switch-switch-2-game-nintendo-eshop-brazil//?igr=eupqs'),
  ('Nintendo eshop 150', 'nintendo-eshop-150', 'Instant Gaming', 'https://www.instant-gaming.com/en/13531-buy-nintendo-eshop-card-150-brl-r-150-card-switch-switch-2-game-nintendo-eshop-brazil//?igr=eupqs'),
  ('Nintendo eshop 250', 'nintendo-eshop-250', 'Instant Gaming', 'https://www.instant-gaming.com/en/13532-buy-nintendo-eshop-card-250-brl-r-250-card-switch-switch-2-game-nintendo-eshop-brazil//?igr=eupqs'),
  ('Nintendo eshop 300', 'nintendo-eshop-300', 'Instant Gaming', 'https://www.instant-gaming.com/en/13533-buy-nintendo-eshop-card-300-brl-r-300-card-switch-switch-2-game-nintendo-eshop-brazil//?igr=eupqs'),
  ('Bloomtown: A Different Story', 'bloomtown-a-different-story', 'Instant Gaming', 'https://www.instant-gaming.com/en/14853-buy-bloomtown-a-different-story-pc-game-steam/?igr=eupqs'),
  ('Trepang2', 'trepang2', 'Instant Gaming', 'https://www.instant-gaming.com/en/9571-buy-trepang2-pc-game-steam/?igr=eupqs'),
  ('Tekken 8', 'tekken-8', 'Instant Gaming', 'https://www.instant-gaming.com/en/9579-buy-tekken-8-pc-game-steam/?igr=eupqs'),
  ('DOOM: The Dark Ages', 'doom-the-dark-ages', 'Instant Gaming', 'https://www.instant-gaming.com/en/16798-buy-doom-the-dark-ages-pc-game-steam/?igr=eupqs'),
  ('Assassin''s Creed Shadows', 'assassin-s-creed-shadows', 'Instant Gaming', 'https://www.instant-gaming.com/en/12831-buy-assassin-s-creed-shadows-pc-ubisoft-connect/?igr=eupqs'),
  ('Blades of Fire', 'blades-of-fire', 'Instant Gaming', 'https://www.instant-gaming.com/en/22604-buy-blades-of-fire-pc-steam/?igr=eupqs'),
  ('Borderlands 4', 'borderlands-4', 'Instant Gaming', 'https://www.instant-gaming.com/en/19682-buy-borderlands-4-pc-steam/?igr=eupqs'),
  ('NBA 2K25', 'nba-2k25', 'Instant Gaming', 'https://www.instant-gaming.com/en/17378-buy-nba-2k25-pc-game-steam-latin-america/?igr=eupqs'),
  ('Sonic Superstars', 'sonic-superstars', 'Instant Gaming', 'https://www.instant-gaming.com/en/14325-buy-sonic-superstars-pc-game-steam/?igr=eupqs'),
  ('The Witness', 'the-witness', 'Instant Gaming', 'https://www.instant-gaming.com/en/1057-buy-the-witness-pc-mac-game-steam/?igr=eupqs'),
  ('Sniper Elite V2 Remastered', 'sniper-elite-v2-remastered', 'Instant Gaming', 'https://www.instant-gaming.com/en/4520-buy-sniper-elite-v2-remastered-remastered-pc-game-steam/?igr=eupqs'),
  ('Horizon Zero Dawn Remastered', 'horizon-zero-dawn-remastered', 'Instant Gaming', 'https://www.instant-gaming.com/en/17919-buy-horizon-zero-dawn-remastered-pc-game-steam-latin-america/?igr=eupqs'),
  ('Copycat', 'copycat', 'Instant Gaming', 'https://www.instant-gaming.com/en/19346-buy-copycat-pc-mac-steam/?igr=eupqs'),
  ('Midnight Fight Express', 'midnight-fight-express', 'Instant Gaming', 'https://www.instant-gaming.com/en/12655-buy-midnight-fight-express-pc-game-steam/?igr=eupqs'),
  ('Octopath Traveler', 'octopath-traveler', 'Instant Gaming', 'https://www.instant-gaming.com/en/4420-buy-octopath-traveler-pc-game-steam/?igr=eupqs'),
  ('Octopath Traveler II', 'octopath-traveler-ii', 'Instant Gaming', 'https://www.instant-gaming.com/en/12870-buy-octopath-traveler-2-pc-game-steam/?igr=eupqs'),
  ('Mortal Kombat 11', 'mortal-kombat-11', 'Instant Gaming', 'https://www.instant-gaming.com/en/3339-buy-mortal-kombat-11-pc-game-steam/?igr=eupqs'),
  ('Ori and the Will of the Wisps', 'ori-and-the-will-of-the-wisps', 'Instant Gaming', 'https://www.instant-gaming.com/en/19582-buy-ori-and-the-will-of-the-wisps-pc-game-steam/?igr=eupqs'),
  ('DREDGE', 'dredge', 'Instant Gaming', 'https://www.instant-gaming.com/en/13688-buy-dredge-pc-game-steam/?igr=eupqs'),
  ('Death Stranding 2: On the Beach', 'death-stranding-2-on-the-beach', 'Instant Gaming', 'https://www.instant-gaming.com/en/21819-buy-death-stranding-2-on-the-beach-pc-steam/?igr=eupqs'),
  ('Slime Rancher', 'slime-rancher', 'Instant Gaming', 'https://www.instant-gaming.com/en/18347-buy-slime-rancher-pc-game-steam-latin-america/'),
  ('God of War Ragnarök', 'god-of-war-ragnarok', 'Instant Gaming', 'https://www.instant-gaming.com/en/17024-buy-god-of-war-ragnarok-pc-game-steam-latin-america/?igr=eupqs'),
  ('God of War', 'god-of-war', 'Instant Gaming', 'https://www.instant-gaming.com/en/17355-buy-god-of-war-pc-game-steam-latin-america/?igr=eupqs'),
  ('Session: Skate Sim', 'session-skate-sim', 'Instant Gaming', 'https://www.instant-gaming.com/en/5735-buy-session-skate-sim-pc-game-steam/?igr=eupqs'),
  ('Uncharted: Legacy of Thieves Collection', 'uncharted-legacy-of-thieves-collection', 'Instant Gaming', 'https://www.instant-gaming.com/en/17533-buy-uncharted-legacy-of-thieves-collection-pc-game-steam-latin-america/?igr=eupqs'),
  ('The Last of Us Part I', 'the-last-of-us-part-i', 'Instant Gaming', 'https://www.instant-gaming.com/en/13960-buy-the-last-of-us-part-i-pc-game-steam-latin-america/?igr=eupqs'),
  ('Marvel''s Spider-Man Remastered', 'marvel-s-spider-man-remastered', 'Instant Gaming', 'https://www.instant-gaming.com/en/11907-buy-marvel-s-spider-man-remastered-pc-game-steam/?igr=eupqs'),
  ('Marvel''s Spider-Man: Miles Morales', 'marvel-s-spider-man-miles-morales', 'Instant Gaming', 'https://www.instant-gaming.com/en/17534-buy-marvel-s-spider-man-miles-morales-pc-game-steam-latin-america/?igr=eupqs'),
  ('Marvel''s Spider-Man 2', 'marvel-s-spider-man-2', 'Instant Gaming', 'https://www.instant-gaming.com/en/18626-buy-marvel-s-spider-man-2-pc-game-steam-latin-america/?igr=eupqs'),
  ('Sackboy: A Big Adventure', 'sackboy-a-big-adventure', 'Instant Gaming', 'https://www.instant-gaming.com/en/18317-buy-sackboy-a-big-adventure-pc-game-steam-latin-america/?igr=eupqs'),
  ('Until Dawn', 'until-dawn', 'Instant Gaming', 'https://www.instant-gaming.com/en/17635-buy-until-dawn-pc-steam/?igr=eupqs'),
  ('Days Gone', 'days-gone', 'Instant Gaming', 'https://www.instant-gaming.com/en/17532-buy-days-gone-pc-game-steam-latin-america/?igr=eupqs'),
  ('The Last of Us Part II Remastered', 'the-last-of-us-part-ii-remastered', 'Instant Gaming', 'https://www.instant-gaming.com/en/18566-buy-the-last-of-us-part-ii-remastered-pc-game-steam-latin-america/?igr=eupqs'),
  ('Returnal', 'returnal', 'Instant Gaming', 'https://www.instant-gaming.com/en/13959-buy-returnal-pc-game-steam-latin-america/?igr=eupqs'),
  ('Stray', 'stray', 'Instant Gaming', 'https://www.instant-gaming.com/en/17217-buy-stray-pc-mac-game-steam-latin-america/?igr=eupqs'),
  ('Max Payne 3', 'max-payne-3', 'Instant Gaming', 'https://www.instant-gaming.com/en/6094-buy-max-payne-3-pc-game-rockstar/?igr=eupqs'),
  ('Tekken 7', 'tekken-7', 'Instant Gaming', 'https://www.instant-gaming.com/en/1515-buy-tekken-7-pc-game-steam/?igr=eupqs'),
  ('Shadow of the Tomb Raider: Definitive Edition', 'shadow-of-the-tomb-raider-definitive-edition', 'Instant Gaming', 'https://www.instant-gaming.com/en/20069-buy-shadow-of-the-tomb-raider-definitive-edition-pc-steam/?igr=eupqs'),
  ('Alien: Isolation', 'alien-isolation', 'Instant Gaming', 'https://www.instant-gaming.com/en/305-buy-alien-isolation-pc-mac-game-steam/?igr=eupqs'),
  ('Assetto Corsa Competizione', 'assetto-corsa-competizione', 'Instant Gaming', 'https://www.instant-gaming.com/en/3153-buy-assetto-corsa-competizione-pc-steam/?igr=eupqs'),
  ('Bramble: The Mountain King', 'bramble-the-mountain-king', 'Instant Gaming', 'https://www.instant-gaming.com/en/13549-buy-bramble-the-mountain-king-pc-game-steam/?igr=eupqs'),
  ('Construction Simulator', 'construction-simulator', 'Instant Gaming', 'https://www.instant-gaming.com/en/12936-buy-construction-simulator-pc-game-steam/?igr=eupqs'),
  ('The Lord of the Rings: Return to Moria', 'the-lord-of-the-rings-return-to-moria', 'Instant Gaming', 'https://www.instant-gaming.com/en/14332-buy-the-lord-of-the-rings-return-to-moria-pc-game-steam/?igr=eupqs'),
  ('Beyond: Two Souls', 'beyond-two-souls', 'Instant Gaming', 'https://www.instant-gaming.com/en/7000-buy-beyond-two-souls-pc-steam/?igr=eupqs'),
  ('LEGO The Incredibles', 'lego-the-incredibles', 'Instant Gaming', 'https://www.instant-gaming.com/en/2510-buy-lego-the-incredibles-pc-mac-game-steam/?igr=eupqs'),
  ('Heavy Rain', 'heavy-rain', 'Instant Gaming', 'https://www.instant-gaming.com/en/6999-buy-heavy-rain-pc-game-steam/?igr=eupqs'),
  ('LEGO Marvel Super Heroes', 'lego-marvel-super-heroes', 'Instant Gaming', 'https://www.instant-gaming.com/en/250-buy-lego-marvel-super-heroes-pc-mac-steam/?igr=eupqs'),
  ('Planet of Lana', 'planet-of-lana', 'Instant Gaming', 'https://www.instant-gaming.com/en/9004-buy-planet-of-lana-pc-game-steam/?igr=eupqs'),
  ('Green Hell', 'green-hell', 'Instant Gaming', 'https://www.instant-gaming.com/en/5639-buy-green-hell-pc-game-steam/?igr=eupqs'),
  ('Celeste', 'celeste', 'Instant Gaming', 'https://www.instant-gaming.com/en/8003-buy-celeste-pc-mac-game-steam/?igr=eupqs'),
  ('Wreckfest', 'wreckfest', 'Instant Gaming', 'https://www.instant-gaming.com/en/582-buy-wreckfest-pc-steam/?igr=eupqs'),
  ('DOOM', 'doom', 'Instant Gaming', 'https://www.instant-gaming.com/en/865-buy-doom-pc-steam/?igr=eupqs'),
  ('Injustice 2', 'injustice-2', 'Instant Gaming', 'https://www.instant-gaming.com/en/1525-buy-injustice-2-pc-game-steam/?igr=eupqs'),
  ('Sea of Stars', 'sea-of-stars', 'Instant Gaming', 'https://www.instant-gaming.com/en/12451-buy-sea-of-stars-pc-game-steam/?igr=eupqs'),
  ('Blasphemous', 'blasphemous', 'Instant Gaming', 'https://www.instant-gaming.com/en/4703-buy-blasphemous-pc-game-steam/?igr=eupqs'),
  ('Outlast 2', 'outlast-2', 'Instant Gaming', 'https://www.instant-gaming.com/en/606-buy-outlast-2-pc-game-steam/?igr=eupqs'),
  ('Have a Nice Death', 'have-a-nice-death', 'Instant Gaming', 'https://www.instant-gaming.com/en/10241-buy-have-a-nice-death-pc-game-steam/?igr=eupqs'),
  ('Mika and the Witch''s Mountain', 'mika-and-the-witch-s-mountain', 'Instant Gaming', 'https://www.instant-gaming.com/en/10397-buy-mika-and-the-witch-s-mountain-pc-game-steam/?igr=eupqs'),
  ('Dead Space (2008)', 'dead-space-2008', 'Instant Gaming', 'https://www.instant-gaming.com/en/338-buy-dead-space-2008-pc-game-ea-app/?igr=eupqs'),
  ('High on Life', 'high-on-life', 'Instant Gaming', 'https://www.instant-gaming.com/en/12163-buy-high-on-life-pc-game-steam/?igr=eupqs'),
  ('Darksiders III', 'darksiders-iii', 'Instant Gaming', 'https://www.instant-gaming.com/en/2061-buy-darksiders-iii-pc-game-steam/?igr=eupqs'),
  ('Resident Evil: Requiem Deluxe Edition', 'resident-evil-requiem-deluxe-edition', 'Instant Gaming', 'https://www.instant-gaming.com/en/20995-buy-resident-evil-requiem-deluxe-edition-pc-steam/?igr=eupqs'),
  ('Resident Evil 4 Gold Edition', 'resident-evil-4-gold-edition', 'Instant Gaming', 'https://www.instant-gaming.com/en/20494-buy-resident-evil-4-gold-edition-pc-steam/?igr=eupqs'),
  ('Crimson Desert Deluxe Edition', 'crimson-desert-deluxe-edition', 'Instant Gaming', 'https://www.instant-gaming.com/en/22143-buy-crimson-desert-deluxe-edition-pc-steam/?igr=eupqs'),
  ('Assetto Corsa Competizione', 'assetto-corsa-competizione-2', 'Instant Gaming', 'https://www.instant-gaming.com/en/3153-buy-assetto-corsa-competizione-pc-steam/?igr=eupqs'),
  ('Forza Horizon 6 Deluxe Edition', 'forza-horizon-6-deluxe-edition', 'Instant Gaming', 'https://www.instant-gaming.com/en/21623-buy-forza-horizon-6-deluxe-edition-pc-xbox-series-x-s-microsoft-store/?igr=eupqs')
on conflict (slug) do nothing;
